<img src=https://lstms-brainybits.s3.ap-south-1.amazonaws.com/green+logo.png width="300" height="200" style="float: left; margin-right: 8px;">

We believe in empowering individuals with the
knowledge and skills they need to become lifelong
learners. Our self-learning website offers a diverse
range of high-quality, interactive courses.
**All rights reserved to BrainyBits. Unauthorized reproduction or distribution of this content is prohibited.** 

# Multiple Linear Regression 

### 1. Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 2. Importing the dataset

In [2]:
dataset = pd.read_csv('Student_Performance.csv')

In [3]:
dataset.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
X

array([[7, 99, 'Yes', 9, 1],
       [4, 82, 'No', 4, 2],
       [8, 51, 'Yes', 7, 2],
       ...,
       [6, 83, 'Yes', 8, 5],
       [9, 97, 'Yes', 7, 0],
       [7, 74, 'No', 8, 1]], dtype=object)

In [6]:
y

array([91., 65., 45., ..., 74., 95., 64.])

### 3. Encoding categorical data

In [7]:
from sklearn.preprocessing import LabelEncoder
X[:, 2] = LabelEncoder().fit_transform(X[:, 2])
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[7 99 1 9 1]
 [4 82 0 4 2]
 [8 51 1 7 2]
 ...
 [6 83 1 8 5]
 [9 97 1 7 0]
 [7 74 0 8 1]]


### 4. Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
X_train

array([[5, 95, 0, 6, 4],
       [2, 98, 0, 7, 4],
       [2, 65, 1, 8, 1],
       ...,
       [1, 76, 1, 6, 5],
       [4, 44, 0, 4, 8],
       [8, 83, 1, 8, 1]], dtype=object)

### 5. Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### 6. Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[50.45 53.  ]
 [53.09 50.  ]
 [78.25 80.  ]
 ...
 [64.57 66.  ]
 [25.9  27.  ]
 [18.83 21.  ]]


In [13]:
y_pred

array([50.45, 53.09, 78.25, ..., 64.57, 25.9 , 18.83])